### ISSUE TITLE
Actualizar deployments de cada Step

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/kubernetes_pipeline#10]
- Agregar afinidad de nodos
  Los nodos tienen un tag `eks.amazonaws.com/nodegroup` que tiene valor `<environment>-pipeline`

  El código que se debe agregar al deployment en la llave `spec.template.spec` es:

  ```yaml
    affinity:
    nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
            - matchExpressions:
                - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                    - staging-pipeline
  ```

- Agregar namespace = `pipeline`
